//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSitem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbKahveEntities : DbContext
    {
        public DbKahveEntities()
            : base("name=DbKahveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hakkimizda> hakkimizda { get; set; }
        public virtual DbSet<kullanici> kullanici { get; set; }
        public virtual DbSet<urunler> urunler { get; set; }
        public virtual DbSet<anasayfa> anasayfa { get; set; }
        public virtual DbSet<magaza> magaza { get; set; }
    }
}
