//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSitem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class kullanici
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "lütfen kullanýcý adýný giriniz!")]
        public string kAd { get; set; }
        [Required(ErrorMessage = "lütfen parolanýzý giriniz!")]
        [DataType(DataType.Password)]
        public string Sifre { get; set; }
        public bool Role { get; set; }
    }
}
